version: '2'

services:
  service1:
    image: httpd:2.4
    ports:
     - "80"
  service2:
    image: httpd:2.4
    ports:
     - "80"
  nginx:
    image: nginx
    ports:
     - "80:80"
    volumes:
     - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
